const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const packing=fs.readFileSync('packing.js','utf8');
const styles=fs.readFileSync('styles.css','utf8');
const reliability=fs.readFileSync('reliability.js','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(app.includes('M3-04.4B'),'app build identity missing');
assert(html.includes('M3-04.4B'),'HTML build identity missing');
assert(styles.includes('screenEntering'),'screen transition missing');
assert(styles.includes(':focus-visible'),'accessible focus style missing');
assert(styles.includes('prefers-reduced-motion'),'reduced motion support missing');
assert(reliability.includes('SMART_STOPS_GRACE_MS'),'Smart Stops grace period missing');
assert(reliability.includes('Initializing'),'friendly initializing state missing');
assert(packing.includes('confettiLayer'),'packing confetti missing');
assert(packing.includes('Emily, you’re Adventure Ready!'),'personalized celebration missing');
assert(packing.includes('adventureCompanionCampfireUnlocked'),'Campfire unlock missing');
assert(app.includes('campfireUnlocked'),'Campfire card missing');
console.log('experience polish tests passed');
